[ALPS08309937] thermal: Use generic thermal_zone_get_trip() function
commit aacfbf15e0ac ("thermal/of: Remove of_thermal_get_crit_temp()")
removed of_thermal_get_trip_points. Fix the following
build break by using generic thermal_zone_get_trip() function

Errors:
drivers/thermal/mediatek/soc_temp_lvts.c:970:16: error: call to undeclared function of_thermal_get_trip_points; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/thermal/mediatek/soc_temp_lvts.c:970:14: error: incompatible integer to pointer conversion assigning to const struct thermal_trip * from int [-Wint-conversion]

MTK-Commit-Id: c3311d57657868e910426f48874ec61a9877b4e2

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: I167c21a9a72ee669eed1ac273536253f093ff29f