[ALPS07875330] imgsensor: add missing headers
Add the missing linux/pinctrl/consumer.h to fix the following
build errors:

errors:
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/gpio/gpio.c:51:20: error: call to undeclared function devm_pinctrl_get; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/gpio/gpio.c:51:18: error: incompatible integer to pointer conversion assigning to struct pinctrl * from int [-Wint-conversion]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/mclk/mclk.c:31:20: error: call to undeclared function devm_pinctrl_get; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/mclk/mclk.c:31:18: error: incompatible integer to pointer conversion assigning to struct pinctrl * from int [-Wint-conversion]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/gpio/gpio.c:76:6: error: call to undeclared function pinctrl_lookup_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/gpio/gpio.c:75:37: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/gpio/gpio.c:94:5: error: call to undeclared function pinctrl_lookup_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/gpio/gpio.c:93:36: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/mclk/mclk.c:53:6: error: call to undeclared function pinctrl_lookup_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/mclk/mclk.c:52:33: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/gpio/gpio.c:155:3: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/mclk/mclk.c:66:7: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/mclk/mclk.c:93:4: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/camera_hw/mclk/mclk.c:164:4: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

MTK-Commit-Id: a1ae65da843bf14134e3dbf59728dfab9f8483e1

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07875330
Feature: Kernel SI Operation
Change-Id: Iae732d7f2ece255323142bcd4d296d1a3c4cb886