[ALPS08309937] devapc: configs: disable CONFIG_MTK_SERROR_HOOK
Disable debug config due to following build error

kernel_device_modules-mainline/drivers/soc/mediatek/devapc/devapc-mtk-multi-ao.c:19:10: fatal error: trace/hooks/traps.h file not found
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

MTK-Commit-Id: 6e67f8bfb962bf715d3b3870cc11a5f561610271

CR-Id: ALPS08309937
Feature: Kernel SI Operation
Signed-off-by: Lili.Lin <lili.lin@mediatek.com>
Change-Id: Iff45685d0835d9a10c63f72a51e9c6654ab1f371