[ALPS08309937] imgsensor: fix the i2c_client probe argument
Follow commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")
to not taking the id argument.

Errors:
drivers/mfd/mt6338-core.c:261:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
sound/soc/codecs/richtek/rt5512.c:1234:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/nfc/st21nfc/st21nfc.c:1250:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
sound/soc/codecs/tfa98xx/src/tfa98xx.c:3247:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
sound/soc/mediatek/common/mtk-sp-spk-amp.c:340:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:4046:12: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/gate_ic/rt4831a_drv.c:364:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/power/supply/rt9759.c:1942:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/power/supply/k6985v1_64_alpha/bq2579x.c:2339:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/mtk_drm_panel_i2c.c:141:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/power/supply/k6985v1_64_alpha/bq28z610.c:555:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/typec/tcpc/tcpc_mt6360.c:2573:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/main2/main2_lens.c:594:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/flashlight/v4l2/k6983v1_64_alpha/sy7806.c:927:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/main/main_lens.c:643:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/flashlight/v4l2/lm3643.c:1025:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/flashlight/v4l2/lm3644.c:1059:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/typec/tcpc/tcpc_rt1711h.c:1613:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/main3/main3_lens.c:574:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/sub/sub_lens.c:576:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/sub2/sub2_lens.c:569:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/cam_cal/src/custom/../common/v2/eeprom_driver.c:452:16: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:205:12: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:217:12: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:229:12: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:242:12: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:256:12: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:270:12: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:284:12: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:298:12: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: 2afed44df8025217c7c1f9fdc1d6ad9d53971b6d

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: Icb09867f6be0c74c3785726fdd4b3e185b14ab82
(cherry picked from commit 2e44528e3f9558a182215a4c8a3064ed6a51e501)