[ALPS08309937] iommu: add gfp flags to iommu_map_sg
Add gfp flags to iommu_map_sg() to fix the build breaks
caused by:
commit d0cbb8cc8d3d ("Merge a13de74e4765 ("Merge tag iommu-updates-v6.3 of git://git.kernel.org/pub/scm/linux/kernel/git/joro/iommu") into android-mainline")

drivers/iommu/mtk_iommu.c:2048:17: error: incompatible function pointer types initializing int (*)(struct iommu_domain *, struct device *) with an expression of type void (struct iommu_domain *, struct device *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/apusys/reviser/2.0/common/reviser_mem.c:123:56: error: too few arguments to function call, expected 6, have 5
drivers/misc/mediatek/apusys/vpu/4.5/vpu_mem.c:305:51: error: too few arguments to function call, expected 6, have 5
drivers/misc/mediatek/apusys/apusys_rv/apu_rproc.c:202:53: error: too few arguments to function call, expected 6, have 5
drivers/misc/mediatek/apusys/apusys_rv/apu_rproc.c:240:37: error: too few arguments to function call, expected 6, have 5

MTK-Commit-Id: 90ed08fdc8671aa3a943b678d5aefcf55f54fdeb

CR-Id: ALPS08309937
Feature: Kernel SI Operation
Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Change-Id: I0d63a5b64d9ff14db3ddbf757ce5b465e502e001