[ALPS09080691] dma-buf: follow dma_heap_ops change
[Description]
fix build error according to 30d2da22a338 ("BACKPORT: FROMLIST: dma-buf/heaps: Correct the types of fd_flags and heap_flags") of kernel-6.6

kernel_device_modules-6.6/drivers/dma-buf/heaps/mtk_system_heap.c:1368:14: error: incompatible function pointer types initializing struct dma_buf *(*)(struct dma_heap *, unsigned long, u32, u64) (aka struct dma_buf *(*)(struct dma_heap *, unsigned long, unsigned int, unsigned long long)) with an expression of type struct dma_buf *(struct dma_heap *, unsigned long, unsigned long, unsigned long) [-Wincompatible-function-pointer-types]

[Test]
sanity/stability

MTK-Commit-Id: 7ec6faa419612d064a1016c2ddd726b2b5359d4b

Signed-off-by: swintegrator <swintegrator@mediatek.com>
Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS09080691
Feature: Kernel SI Operation
Change-Id: If6e3dde232a8d62d22f065cb80c7c52b8e766bb0