[ALPS08309937] pinctrl: Stop using ARCH_NR_GPIOS
ARCH_NR_GPIOS is removed by
commit 7b61212f2a07 ("gpiolib: Get rid of ARCH_NR_GPIOS")

Follow commit 95b39792c664 ("gpio: aggregator: Stop using ARCH_NR_GPIOS")
to fix the following build errors:

drivers/pinctrl/mediatek/pinctrl-mtk-common-v2_debug.c:29:21: error: use of undeclared identifier ARCH_NR_GPIOS
drivers/pinctrl/mediatek/pinctrl-mtk-common-v2_debug.c:506:21: error: use of undeclared identifier ARCH_NR_GPIOS

MTK-Commit-Id: ad1c365a48bfa409815ed282e02204ddc1d312d4

Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: I964e9a72ca160bc195805b5e3381e14e8468790e