[ALPS08309937] ASoC: fix the i2c_client probe argument
Follow commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")
to not taking the id argument.

Errors:
sound/soc/codecs/richtek/rt5512.c:1234:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
sound/soc/codecs/tfa98xx/src/tfa98xx.c:3247:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: 3898d98f59d7f329b2a3ccd8c5b946a0de236586

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: I2eac4de1c28328b534629a52d540ca6441980860
(cherry picked from commit 49de61196398ce18fef9fe581b84766efc4d7c27)