[ALPS08606670] fix kernel-6.6 build error
kernel_device_modules-6.6/drivers/misc/mediatek/trusted_mem/tests/
ut_common.c:416:2: error: no matching function for call to strscpy
        strscpy(sec_heap_name, "mtk_tee_page-uncached");

kernel-6.6/include/linux/fortify-string.h:292:26: note: candidate
function not viable: requires 3 arguments, but 2 were provided
__FORTIFY_INLINE ssize_t strscpy(char * const POS p,
const char * const POS q, size_t size)

kernel_device_modules-6.6/drivers/misc/mediatek/trusted_mem/ffa_v11/
bus.c:101:13: error: incompatible function pointer types initializing
int (*)(const struct device *, struct kobj_uevent_env *) with an
expression of type int (struct device *, struct kobj_uevent_env *)
[-Wincompatible-function-pointer-types]
        .uevent         = ffa_device_uevent,

MTK-Commit-Id: f5cb4eb63a2e2d994da7b2554c26f44244f780e6

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08606670
Feature: Kernel SI Operation
Change-Id: I73f04fde58a516661a9850afe5c1459519705c35