[ALPS08309937] configs: fix build error
Disabling following configs as they have conflict with GKI
CONFIG_PINCTRL_MT7981
CONFIG_COMMON_CLK_MT7981
CONFIG_COMMON_CLK_MT8167
CONFIG_COMMON_CLK_MT8188

ERROR: modpost: ../kernel_device_modules-mainline/drivers/clk/mediatek/clk-common: mtk_alloc_clk_data exported twice. Previous export was in vmlinux
ERROR: modpost: ../kernel_device_modules-mainline/drivers/clk/mediatek/clk-common: mtk_free_clk_data exported twice. Previous export was in vmlinux
ERROR: modpost: ../kernel_device_modules-mainline/drivers/clk/mediatek/clk-common: mtk_clk_register_fixed_clks exported twice. Previous export was in vmlinux
...

ERROR: modpost: ../kernel_device_modules-mainline/drivers/pinctrl/mediatek/pinctrl-mtk-v2: mtk_hw_set_value exported twice. Previous export was in vmlinux
ERROR: modpost: ../kernel_device_modules-mainline/drivers/pinctrl/mediatek/pinctrl-mtk-v2: mtk_hw_get_value exported twice. Previous export was in vmlinux

ERROR: The following kernel modules are built but not copied. Add these lines to the module_outs attribute of @//kernel_device_modules-mainline:mgk_64_kmainline_kernel_aarch64.userdebug:
    "drivers/clk/mediatek/clk-mt8188-topckgen.ko",
    "drivers/clk/mediatek/clk-mt8188-peri_ao.ko",
    "drivers/clk/mediatek/clk-mt8188-vdo0.ko",
    "drivers/clk/mediatek/clk-mt8188-vdo1.ko",
    "drivers/clk/mediatek/clk-mt8188-ipe.ko",
    "drivers/clk/mediatek/clk-mt8188-imp_iic_wrap.ko",
    "drivers/clk/mediatek/clk-mt8188-infra_ao.ko",
    "drivers/clk/mediatek/clk-mt8188-apmixedsys.ko",
    "drivers/clk/mediatek/clk-mt8188-cam.ko",
    "drivers/clk/mediatek/clk-mt8188-wpe.ko",
    "drivers/clk/mediatek/clk-mt8188-ccu.ko",
    "drivers/clk/mediatek/clk-mt8188-adsp_audio26m.ko",
    "drivers/clk/mediatek/clk-mt8188-venc.ko",
    "drivers/clk/mediatek/clk-mt8188-vdec.ko",
    "drivers/clk/mediatek/clk-mt8188-mfg.ko",
    "drivers/clk/mediatek/clk-mt8188-vpp0.ko",
    "drivers/clk/mediatek/clk-mt8188-img.ko",
    "drivers/clk/mediatek/clk-mt8188-vpp1.ko",

MTK-Commit-Id: 3f57d46fc51d236932b2118b65b21bf622c2f464

CR-Id: ALPS08309937
Feature: Kernel SI Operation
Signed-off-by: Lili.Lin <lili.lin@mediatek.com>
Change-Id: If313528d6805ab0ebd5f7d25d5d40f3906243a76