[ALPS09102562] sched: follow em_perf_domain change
[Description]
fix build error according to 3a759c566571 ("UPSTREAM: PM: EM: Remove old table") of kernel-6.6

kernel_device_modules-6.6/drivers/misc/mediatek/pbm/mtk_pbm.c:177:32: error: no member named table in struct em_perf_domain
kernel_device_modules-6.6/drivers/misc/mediatek/pbm/mtk_pbm.c:192:31: error: no member named table in struct em_perf_domain

[Test]
sanity/stability

MTK-Commit-Id: ff7b16ad30f6672937febd2715033d0d4fbb594a

Signed-off-by: swintegrator <swintegrator@mediatek.com>
Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS09102562
Feature: Kernel SI Operation
Change-Id: I1746991370e13919720f4ecb8762f78cc91a78b4