[ALPS08878903] sched: fix softirq build error
[Description]
fix 32-bit project build error due to bb7ba5f5a231 ("FROMLIST: sched: Avoid placing RT threads on cores handling long softirqs") in kernel-6.6

ld.lld: error: duplicate symbol: active_softirqs
>>> defined at softirq.c
>>>            kernel/softirq.o:(active_softirqs) in archive vmlinux.a
>>> defined at eas_plus.c
>>>            ../kernel/kernel_device_modules-6.6/drivers/misc/mediatek/sched/eas/eas_plus.o:(.data..percpu+0x0) in archive vmlinux.a

[Test]
build pass

MTK-Commit-Id: 2ac135a897370484c47ac0f25c95d6b757f0a393

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08878903
Feature: Kernel SI Operation
Change-Id: Id97fc2e2a95b74754db1d875c366fe9e498c57ec