[ALPS09245217] fix build error due to mainline migration
[Description]
Fix build error according to Commit "cf4978e ANDROID: Build GKI with CONFIG_KUNIT=m"

ERROR: The following kernel modules are built but not copied. Add these lines to the module_outs attribute of @//kernel_device_modules-mainline:mgk_64_kmainline_kernel_aarch64.userdebug:
    "drivers/base/regmap/regmap-kunit.ko",
    "drivers/base/regmap/regmap-raw-ram.ko",
    "drivers/base/regmap/regmap-ram.ko",
    "lib/kunit/kunit-test.ko",
    "drivers/iio/test/iio-test-format.ko",
    "sound/soc/soc-topology-test.ko",
    "drivers/clk/clk-gate_test.ko",
    "drivers/clk/clk_test.ko",
    "lib/kunit/kunit.ko",
    "drivers/input/tests/input_test.ko",
    "net/core/dev_addr_lists_test.ko",
    "sound/soc/soc-utils-test.ko",
    "drivers/hid/hid-uclogic-test.ko",
    "lib/kunit/kunit-example-test.ko",
    "kernel/time/time_test.ko",
    "fs/ext4/ext4-inode-test.ko",
    "drivers/rtc/lib_test.ko",
    "fs/fat/fat_test.ko",

[Test]
Build and Boot up

MTK-Commit-Id: 5e4bf628cc415e209db82968e0aac2c82bb4a1d3

Signed-off-by: swintegrator <swintegrator@mediatek.com>
Signed-off-by: Clive Lin <clive.lin@mediatek.com>
Signed-off-by: PoShao Chen <poshao.chen@mediatek.com>
CR-Id: ALPS09245217
Feature: Kernel SI Operation
Change-Id: I6d8ec26cfdcbf30a2b952ef0b5204a524c866392