[ALPS07875330] pinctrl: add missing headers
Add the missing linux/pinctrl/consumer.h to fix the following
build errors:

errors:
drivers/pinctrl/mediatek/pinctrl-paris.c:898:9: error: call to undeclared function pinctrl_gpio_direction_input; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/pinctrl/mediatek/pinctrl-paris.c:911:9: error: call to undeclared function pinctrl_gpio_direction_output; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/pinctrl/mediatek/pinctrl-paris.c:1570:9: error: call to undeclared function pinctrl_gpio_direction_input; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/pinctrl/mediatek/pinctrl-paris.c:1583:9: error: call to undeclared function pinctrl_gpio_direction_output; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

MTK-Commit-Id: 180de1f35550c414abefcb929cd734a8edd02dca

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07875330
Feature: Kernel SI Operation
Change-Id: Ib319e29167ee03c02e25608f4bfc81f48399966f