[ALPS08309937] sound: fix build break
1. struct class error
commit 2df418cf4b "driver core: class: remove subsystem private pointer from struct class"
has stopped user from using subsystem private pointer directly.
Hence, we use class_create_file_ns instead since it provides handling private pointer.

sound/soc/codecs/richtek/richtek_spm_cls.c:591:50: error: no member named p in struct class
                ret = sysfs_create_file_ns(&richtek_spm_class->p->subsys.kobj,
                                            ~~~~~~~~~~~~~~~~~  ^

2. gpio_set_debounce
follow commit 0e685c3e71 "gpiolib: remove gpio_set_debounce()"

3. struct class as a constant
commit 75a2d4226b537 "driver core: class: mark the struct class for sysfs callbacks as constant"
and several other changes has changed APIs to take a constant struct class

4. stop_dma_first
commit 099770e2dae0 "ASoC: remove old trigger ordering method"
has removed stop_dma_first

MTK-Commit-Id: 1f5e64a4e4fa9d3461b6902686398360dcfe6c4b

CR-Id: ALPS08309937
Feature: Kernel SI Operation
Signed-off-by: Lili.Lin <lili.lin@mediatek.com>
Change-Id: I9e2d78e325812fee0aec431127380ccedaefd8cc