[ALPS08490829] ASoC: mediatek: Convert to generic PCM copy ops
Fix the build errors according to Commit 95396d83e96c ("ASoC: mediatek: Convert to generic PCM copy ops")

kernel_device_modules-mainline/sound/soc/mediatek/mt6989/mt6989-afe-pcm.c:5275:3: error: field designator copy_user does not refer to any field in type const struct snd_soc_component_driver
        .copy_user = mtk_afe_pcm_copy_user,
        ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

MTK-Commit-Id: e1a0c6c4b122a41c455f6058e1d95b7382643751

CR-Id: ALPS08490829
Feature: Kernel SI Operation
Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Change-Id: Iebe44bae939d9dec94ddf5e35eabf9a99a7033d2