[ALPS08309937] typec: fix the i2c_client probe argument
Follow commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")
to not taking the id argument.

Errors:
drivers/misc/mediatek/typec/tcpc/tcpc_mt6360.c:2573:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/typec/tcpc/tcpc_rt1711h.c:1613:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: 000011def8f3e6100d28b927d3d97f886df8a14b

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: Ic682077a8d2d4041e81066fe773e82e73690a9c1
(cherry picked from commit b88fff9ecdc0ee20bd8087fca6e901e3ef8d0a87)