[ALPS08490829] Fix v4l2_async build error
Fix the build error due to Commit adb2dcd5f2d4 ("media: v4l: async: Rename v4l2_async_subdev as v4l2_async_connection") and Commit bda8953e8c3e ("media: v4l: async: Drop v4l2_async_nf_parse_fwnode_endpoints()")

kernel_device_modules-mainline/drivers/misc/mediatek/lens/vcm/v4l2/media/mtk-composite.h:23:27: error: field has incomplete type struct v4l2_async_subdev
        struct v4l2_async_subdev asd;
                                 ^
kernel_device_modules-mainline/drivers/misc/mediatek/lens/vcm/v4l2/media/mtk-composite.c:175:7: error: call to undeclared function v4l2_async_nf_parse_fwnode_endpoints; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        rc = v4l2_async_nf_parse_fwnode_endpoints
             ^
kernel_device_modules-mainline/drivers/misc/mediatek/flashlight/mtk-composite.h:23:27: error: field has incomplete type struct v4l2_async_subdev
        struct v4l2_async_subdev asd;
                                 ^
kernel_device_modules-mainline/drivers/misc/mediatek/flashlight/mtk-composite.c:175:7: error: call to undeclared function v4l2_async_nf_parse_fwnode_endpoints; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        rc = v4l2_async_nf_parse_fwnode_endpoints
             ^
vendor/mediatek/kernel_modules/mtkcam/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:2424:8: error: call to undeclared function v4l2_async_nf_parse_fwnode_endpoints; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        ret = v4l2_async_nf_parse_fwnode_endpoints
              ^
vendor/mediatek/kernel_modules/mtkcam/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:2425:19: error: invalid application of sizeof to an incomplete type struct v4l2_async_subdev
                (dev, notifier, sizeof(struct v4l2_async_subdev), NULL);
                                ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~

MTK-Commit-Id: 08fc6dfa34bf264982e080bff9c73eb50cd5ba20

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08490829
Feature: Kernel SI Operation5
Change-Id: Ib9f4addcca3397125318da80be5cfd92719b71ed