[ALPS08878903] sched: fix build error
[Description]
d62eeedb14a6 ("ANDROID: Zap kernel/sched/android.h stubs") in kernel-6.6 removes task_may_not_preempt.
Add this function back to fix build error:
kernel_device_modules-6.6/drivers/misc/mediatek/sched/eas/rt.c:386:10: error: call to undeclared function task_may_not_preempt; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

[Test]
boot pass

MTK-Commit-Id: 646c4124f0a2865b21adf3c91a65f85e020a4b7d

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08878903
Feature: Kernel SI Operation
Change-Id: I41354f915fac416ce13e110e4d21f99d593ad349