[ALPS08309937] touchscreen: add missing headers
Add the missing linux/pinctrl/consumer.h to fix the following
build errors:

errors:
drivers/input/touchscreen/GT9895/goodix_brl_hw.c:241:10: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9895/goodix_brl_hw.c:268:7: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:1340:23: error: call to undeclared function devm_pinctrl_get; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:1340:21: error: incompatible integer to pointer conversion assigning to struct pinctrl * from int [-Wint-conversion]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:1349:36: error: call to undeclared function pinctrl_lookup_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:1349:34: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:1360:32: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:1371:32: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:1383:33: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:1394:33: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:1407:2: error: call to undeclared function pinctrl_put; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:1417:7: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:1439:7: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:2242:7: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:2300:3: error: call to undeclared function pinctrl_put; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9895/goodix_ts_core.c:1465:23: error: call to undeclared function devm_pinctrl_get; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9895/goodix_ts_core.c:1465:21: error: incompatible integer to pointer conversion assigning to struct pinctrl * from int [-Wint-conversion]
drivers/input/touchscreen/GT9895/goodix_ts_core.c:1474:36: error: call to undeclared function pinctrl_lookup_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9895/goodix_ts_core.c:1474:34: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/GT9895/goodix_ts_core.c:1485:32: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/GT9895/goodix_ts_core.c:1496:32: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/GT9895/goodix_ts_core.c:1508:33: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/GT9895/goodix_ts_core.c:1519:33: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/GT9895/goodix_ts_core.c:1532:2: error: call to undeclared function pinctrl_put; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9895/goodix_ts_core.c:1542:7: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9895/goodix_ts_core.c:1564:7: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/GT9895/goodix_ts_core.c:2394:9: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:1415:34: error: call to undeclared function pinctrl_lookup_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:1415:32: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:1418:33: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:1421:34: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:1424:35: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:1438:11: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:1442:11: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:1454:11: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:1458:11: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:3214:26: error: call to undeclared function devm_pinctrl_get; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:3214:24: error: incompatible integer to pointer conversion assigning to struct pinctrl * from int [-Wint-conversion]

MTK-Commit-Id: 5bf15a262a61400f80e9f7adf164403e1681bd70

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: Id1089cf71f093c9a130a085d1c772a10e46735ca