[ALPS08309937] battery: fix the i2c_client probe argument
Follow commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")
to not taking the id argument.

Errors:
drivers/power/supply/rt9759.c:1942:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/power/supply/k6985v1_64_alpha/bq2579x.c:2339:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/power/supply/k6985v1_64_alpha/bq28z610.c:555:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: 6cca039c83d34fe0156a67fca24d48504524e1eb

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: Id6b571e3e0727d7630d3b4f94e1ec4b768bf0387
(cherry picked from commit a0195a386fab9a61659cf2246191b3f99811e42c)