[ALPS08687112] fhctl: fix kernel-6.6 build error
Kernel Commit 78b7fb432ac1 ("ANDROID: gki_defconfig: Enable
CONFIG_PROVE_LOCKING for android-mainline") removes CONFIG_KALLSYMS_ALL,
and it breaks the definition of "NO_OPTIMIZE" in clk-fhctl.h.

Fix build error:
kernel_device_modules-6.6/drivers/clk/mediatek/clk-fhctl.c:44:35: error:
expected ; after top level declarator
static struct pll_dts *NO_OPTIMIZE get_dts_array(void) { return _array; }

MTK-Commit-Id: 07e484a25435390b82d3ef9091719c1c8a2544be

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08687112
Feature: Kernel SI Operation
Change-Id: I8cc78c1a79ea687dc5c083d8459287e8331bb1eb