[ALPS07875330] sound: add missing headers
Add the missing linux/pinctrl/consumer.h to fix the following
build errors:

errors:
sound/soc/codecs/mt6368-accdet.c:2232:20: error: call to undeclared function devm_pinctrl_get; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
sound/soc/codecs/mt6368-accdet.c:2232:18: error: incompatible integer to pointer conversion assigning to struct pinctrl * from int [-Wint-conversion]
sound/soc/codecs/mt6368-accdet.c:2238:17: error: call to undeclared function pinctrl_lookup_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
sound/soc/codecs/mt6368-accdet.c:2238:15: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
sound/soc/codecs/mt6368-accdet.c:2242:20: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
sound/soc/codecs/mt6368-accdet.c:2248:2: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
sound/soc/codecs/mt6338-accdet.c:2156:20: error: call to undeclared function devm_pinctrl_get; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
sound/soc/codecs/mt6338-accdet.c:2156:18: error: incompatible integer to pointer conversion assigning to struct pinctrl * from int [-Wint-conversion]
sound/soc/codecs/mt6338-accdet.c:2162:17: error: call to undeclared function pinctrl_lookup_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
sound/soc/codecs/mt6338-accdet.c:2162:15: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
sound/soc/codecs/mt6338-accdet.c:2166:20: error: incompatible integer to pointer conversion assigning to struct pinctrl_state * from int [-Wint-conversion]
sound/soc/codecs/mt6338-accdet.c:2172:2: error: call to undeclared function pinctrl_select_state; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

MTK-Commit-Id: edb6ff5126236334f6f18cbaabc36c75b1423202

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07875330
Feature: Kernel SI Operation
Change-Id: I2fd75137ff12ae7b2948b87934752224eb377bc5