[ALPS08712363] MT6893: Kernel-6.6 build error fix
isp_60/videobuf2-dma-contig.c:298:16: error: use of undeclared identifier lock

MTK-Commit-Id: 66afe671a8c94123096eead9983cd6fc42419a1f

Change-Id: Ic3b9517ee19297c92402d03972f98dd927b498c8
CR-Id: ALPS08712363
Feature: [Android Default] Camera Application Basic Functions
Signed-off-by: vikas.saharawat <vikas.saharawat@mediatek.com>
(cherry picked from commit 21fc04140e46902b12a28956aec44c79d8d872c9)