[ALPS08309937] nfc: fix the i2c_client probe argument
Follow commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")
to not taking the id argument.

Errors:
drivers/misc/mediatek/nfc/st21nfc/st21nfc.c:1250:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: 1b6049c4d0d54fe70a275ab7e8a94523c8611aba

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: I58e1b020a528547882a1e10c9109741380556f4e
(cherry picked from commit 97f0d97aeb0f9606bf40ddd3e116d5ce0558bb94)