[ALPS08309937] pinctrl: fix no member named of_node in struct gpio_chip
Fix the build breaks caused by
commit 70d0fc4288da ("gpiolib: Get rid of not used of_node member")

Errors:
drivers/pinctrl/mediatek/pinctrl-paris.c:969:8: error: no member named of_node in struct gpio_chip; did you mean fwnode?
drivers/pinctrl/mediatek/pinctrl-paris.c:1604:8: error: no member named of_node in struct gpio_chip; did you mean fwnode?

MTK-Commit-Id: 4af4dccec92dfd242fb9a687be2e50a40a27f2eb

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: I18335f63866f397257f3271f6dd27f6cf1a30432
(cherry picked from commit 04ce4dd2786c2a4164ab8aa07f62b36463b76acb)