[ALPS08490829] drm/prime: fix build error
Fix the build error due to Commit 71a7974ac701 ("drm/prime: Unexport helpers for fd/handle conversion") and Commit 0adec22702d4 ("drm: Remove struct drm_driver.gem_prime_mmap")

kernel_device_modules-mainline/drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_drv.c:7836:24: error: use of undeclared identifier drm_gem_prime_handle_to_fd
        .prime_handle_to_fd = drm_gem_prime_handle_to_fd,
                              ^
kernel_device_modules-mainline/drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_drv.c:7837:24: error: use of undeclared identifier drm_gem_prime_fd_to_handle
        .prime_fd_to_handle = drm_gem_prime_fd_to_handle,
                              ^
kernel_device_modules-mainline/drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_drv.c:7838:3: error: field designator gem_prime_mmap does not refer to any field in type struct drm_driver
        .gem_prime_mmap = mtk_drm_gem_mmap_buf,
        ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

MTK-Commit-Id: 4cdb626ba60c93cbcec274201ba3608e8d70a7e8

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08490829
Feature: Kernel SI Operation
Change-Id: I3477683177f914e20a907023583d2890b28956db