[ALPS07875330] pinctrl: add missing seq_file.h header
Add the missing include/linux/seq_file.h to fix the following
build errors:

errors:
drivers/pinctrl/mediatek/pinctrl-paris.c:703:2: error: call to undeclared function seq_printf; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/pinctrl/mediatek/pinctrl-paris.c:1488:3: error: call to undeclared function seq_printf; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

MTK-Commit-Id: b9315b30aaf8134d0b7c612bf38333a423529a13

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07875330
Feature: Kernel SI Operation
Change-Id: Ib73e40c99f3e4ef742f36b6c6fe4e8b458af7e2e