[ALPS09045970] logstore: fix namespace build error
[Description]
fix namespace build error due to a38b207d4f4e of kernel-6.6

ERROR: modpost: module log_store uses symbol end_buffer_write_sync from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module log_store uses symbol __brelse from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.

[Test]
sanity/stability pass

MTK-Commit-Id: ba13ca3f8b294bda0cc2d3cb73eec5e6296587bf

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS09045970
Feature: Kernel SI Operation
Change-Id: I23dc848052d4c3974e85deab44f4f29cb6f9be03