[ALPS08309937] iommu: remove detach_dev
Remove detach_dev to fix the build breaks
caused by:
commit 8f9930fa0161 ("iommu: Remove detach_dev callback")

Errors:
drivers/iommu/mtk_iommu.c:2048:4: error: field designator detach_dev does not refer to any field in type const struct iommu_domain_ops; did you mean attach_dev?
drivers/iommu/mtk_iommu.c:2048:17: error: incompatible function pointer types initializing int (*)(struct iommu_domain *, struct device *) with an expression of type void (struct iommu_domain *, struct device *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: 9daee83ad72aa94f34e17a455e6f79de68b1fadc

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: I70711d9805aa2f4db590a33ec3810878580ecc15