[ALPS08309937] dpe: remove the use of dma_buf lock
commit 28743e25fa1c ("dma-buf: Remove obsoleted internal lock")
removes the internal lock from dma_buf, so follow it to remove
the use of lock lock to fix the following errors:

errors:
drivers/misc/mediatek/cameraisp/dpe/isp_7s/videobuf2-dma-contig.c:
289:43: error: no member named lock in struct dma_buf
drivers/misc/mediatek/cameraisp/dpe/isp_70/videobuf2-dma-contig.c:
288:43: error: no member named lock in struct dma_buf

MTK-Commit-Id: 46ef0a93216db89ebf0901eb7179c75d0b4c664b

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: Ifa518ee8db392c7deb4ad8e6d2b5957b08f3483c
(cherry picked from commit 4d1e399f017ad190e0736f04e27c071bf65d6db9)