[ALPS08309937] regulator: add DEVICE_MODULES
To resolve build error because GKI also has rt4803

ERROR: The following kernel modules are built but not copied. Add these lines to the module_outs attribute of @//kernel_device_modules-mainline:mgk_64_kmainline_kernel_aarch64.userdebug:
    "drivers/regulator/rt4803.ko",

MTK-Commit-Id: 1029edb6aa63d7d26163c75b8d9571f759a804f0

CR-Id: ALPS08309937
Feature: Kernel SI Operation
Signed-off-by: Lili.Lin <lili.lin@mediatek.com>
Change-Id: Id2b86891f090cff36371fc21db98ea578a081283