[ALPS08732781] kernel: configs: disable CONFIG_PRINTK_INDEX
[Description]
Fix build error caused by commit ff9fc702b8c3 ("ANDROID: Kleaf: Switch to Clang 18.0.0 (r510928)")

kernel-6.6/include/linux/gfp.h:223:2: error: unused variable _entry_ptr [-Werror,-Wunused-variable]
...
kernel-6.6/include/linux/printk.h:395:34: note: expanded from macro __printk_index_emit
  395 |                         static const struct pi_entry *_entry_ptr
      |                                                       ^~~~~~~~~~.

[Test]
build and boot pass

MTK-Commit-Id: b056233a8bc2ee777b7f63474602b12a55a89218

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08732781
Feature: Kernel SI Operation
Change-Id: I647633c686596ab26837e918f6e93d138e0d8633