[ALPS08687112] sched: fix kernel-6.6 build error
kernel commit f95a8df7f036 changes the interface of
android_rvh_check_preempt_wakeup, so follow this change in
kernel_device_modules-6.6/drivers/misc/mediatek/sched/eas/vip.c

Build error:
kernel_device_modules-6.6/drivers/misc/mediatek/sched/eas/vip.c:780:56:
error: incompatible function pointer types passing void (void *, struct
rq *, struct task_struct *, bool *, bool *, int, struct sched_entity *,
struct sched_entity *, int, unsigned int) (aka void (void *, struct
rq *, struct task_struct *, _Bool *, _Bool *, int, struct sched_entity *,
struct sched_entity *, int, unsigned int)) to parameter of type void (*)
(void *, struct rq *, struct task_struct *, bool *, bool *, int, struct
sched_entity *, struct sched_entity *, int) (aka void (*)(void *, struct
rq *, struct task_struct *, _Bool *, _Bool *, int, struct sched_entity *,
struct sched_entity *, int)) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: e7fa3ebfe5f5a1494e19f8900a41ab6429745b0f

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08687112
Feature: Kernel SI Operation
Change-Id: I0c7cd89760e8a646f9329fe281d00ca6537cf942