[ALPS08309937] EEPROM: fix the i2c_client probe argument
Follow commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")
to not taking the id argument.

Errors:
drivers/misc/mediatek/cam_cal/src/custom/../common/v2/eeprom_driver.c:452:16: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: 532043b884d597b7b8a5e9f080e5d605585ba44e

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: Id57b5b3a78ffe497639881015bc2d859e8d69bdb
(cherry picked from commit 63822500fe8ea0a2e577b1afbe101bcdad415bee)