[ALPS08309937] lcm: fix the i2c_client probe argument
Follow commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")
to not taking the id argument.

Errors:
drivers/gpu/drm/panel/mtk_drm_panel_i2c.c:141:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: 045513c994eb347b176864ce3499fbdb754c7298

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: I1cab63a28bf9feb0654bdd0d692f4e405b923431
(cherry picked from commit fbc43956d6fec123eca55253605a5535a2e876e6)