[ALPS07880779] ufs: add missing arm headers
commit 229d58e31678 ("firmware: arm_ffa: Move constants to header file")
moves some constants to headers, include them to fix the following
build errors:

drivers/scsi/ufs/ufs-mediatek-sip.h:63:2: error: call to undeclared function arm_smccc_smc; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/scsi/ufs/ufs-mediatek-sip.h:63:16: error: call to undeclared function ARM_SMCCC_CALL_VAL; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/scsi/ufs/ufs-mediatek-sip.h:63:16: error: use of undeclared identifier ARM_SMCCC_FAST_CALL
drivers/scsi/ufs/ufs-mediatek-sip.h:63:16: error: use of undeclared identifier ARM_SMCCC_SMC_64
drivers/scsi/ufs/ufs-mediatek-sip.h:63:16: error: use of undeclared identifier ARM_SMCCC_OWNER_SIP
drivers/phy/mediatek/phy-mtk-ufs.c:189:23: error: variable has incomplete type struct arm_smccc_res
drivers/phy/mediatek/phy-mtk-ufs.c:203:23: error: variable has incomplete type struct arm_smccc_res
drivers/phy/mediatek/phy-mtk-ufs.c:217:23: error: variable has incomplete type struct arm_smccc_res
drivers/phy/mediatek/phy-mtk-ufs.c:234:23: error: variable has incomplete type struct arm_smccc_res

MTK-Commit-Id: 2c033456f270d62400c5daccc95da020930f7521

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07880779
Feature: Kernel SI Operation
Change-Id: I2ad76d9534ce592ee0389c7e4a9e62647c614541