[ALPS08309937] mfd: fix the i2c_client probe argument
Follow commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")
to not taking the id argument.

Errors:
drivers/mfd/mt6338-core.c:261:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: b24cfd43aaf310162cb703ff0ff79cbd0f5a205a

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: Ice01785ad409b75dadab7d7686f18a25597f96fd
(cherry picked from commit 1f066808d5bea7e919dab56e389b3724b5c52c16)