[ALPS08490829] spi: use SPI_CONTROLLER functions
Fix the build error due to Commit 90366cd60133 ("spi: Get rid of old SPI_MASTER_MUST_TX & SPI_MASTER_MUST_RX").

kernel_device_modules-mainline/drivers/spi/spi-mt65xx.c:1508:20: error: use of undeclared identifier SPI_MASTER_MUST_RX
                master->flags |= SPI_MASTER_MUST_RX;
                                 ^
kernel_device_modules-mainline/drivers/spi/spi-mt65xx.c:1510:20: error: use of undeclared identifier SPI_MASTER_MUST_TX
                master->flags |= SPI_MASTER_MUST_TX;
                                 ^

MTK-Commit-Id: 219e601fb62770e948b50555e807fe7cc3b15b2c

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08490829
Feature: Kernel SI Operation
Change-Id: If3c7b463b2a446a6eb59bdb057bcee3f38bffd57