[ALPS08309937] lens: fix the i2c_client probe argument
Follow commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")
to not taking the id argument.

Errors:
drivers/misc/mediatek/lens/vcm/proprietary/main3/main3_lens.c:574:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/sub2/sub2_lens.c:569:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/main2/main2_lens.c:594:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/sub/sub_lens.c:576:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/main/main_lens.c:643:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: 71ea5cf7c6d93b655a0f5db38233800cf2b1e273

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: I8e27b790789e813e5ac16797ce4dc37bd06dbd24
(cherry picked from commit 4e0562e9b2c9331c120d150500dfe102d62b5ec5)