[ALPS08309937] sound: fix the i2c_client probe argument
Follow commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")
to not taking the id argument.

Errors:
sound/soc/mediatek/common/mtk-sp-spk-amp.c:340:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: 8983fcd7c7dcbaaefd96cb9e76a6dd0d093d3474

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: If5d2514ffd1167d4423f450e1259cb2a0da85b0e
(cherry picked from commit 6b64bdc7c53f1c66d1118c42a1a36f04a171df02)