[ALPS08309937] gate_ic: fix the i2c_client probe argument
Follow commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")
to not taking the id argument.

Errors:
drivers/misc/mediatek/gate_ic/rt4831a_drv.c:364:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: 4afcd39d0b4c4cd603b714ee5401901af4032705

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: I65d3386b2966d661a522d5107075701d51c39a45
(cherry picked from commit e1aabc21c2402e3a93d1a5acf66ad918c07710bb)