[ALPS08309937] eccci: include clock.h
Include clock.h to fix the following build breaks

Errors:
drivers/misc/mediatek/eccci/hif/ccci_hif.c:293:6: error: call to undeclared function local_clock; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/hif/ccci_hif.c:306:45: error: call to undeclared function local_clock; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/port/port_smem.c:252:35: error: call to undeclared function local_clock; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/port/port_smem.c:346:31: error: call to undeclared function local_clock; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/port/port_proxy.c:426:9: error: call to undeclared function local_clock; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/port/port_proxy.c:735:12: error: call to undeclared function local_clock; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/port/port_proxy.c:808:12: error: call to undeclared function local_clock; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/port/port_proxy.c:854:12: error: call to undeclared function local_clock; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/port/port_proxy.c:982:15: error: call to undeclared function sched_clock; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/fsm/md_sys1_platform.c:1400:34: error: call to undeclared function sched_clock; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

MTK-Commit-Id: f4098d0accfb9ceacf18434d4e4123803657e823

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: I053d3678c0f5c3525c1580a806fbd5baeb9b8654
(cherry picked from commit 6ca31e1f4db657e6e79404459d5527a0e4192edc)