[ALPS08631203] fix build error due to mainline migration
[Description]
Fix build error according to Commit "4cf6336 Merge tag v6.10-rc1 into android-mainline"
1. include linux/vmalloc, error: call to undeclared function vfree, vmalloc, vzalloc
2. fix error due to "use $(src) instead of $(srctree)/$(src) for source directory"
3. remove second parameter of __assign_str()
4. error: const type qualifier on return type has no effect
5. mtk_vcodec_dec.c:1709:26: error: no member named num_buffers in struct vb2_queue (mtk_vcodec_enc.c)
6. cqhci-core.c:479:13: error: static declaration of cqhci_set_tran_desc follows non-static declaration
7. mbraink_process.c:178:64: error: parameter current_tid set but not used [-Werror,-Wunused-but-set-parameter]
8. mtk_thermal_monitor.c:1386:87: error: parameter temp set but not used [-Werror,-Wunused-but-set-parameter]
9. bypass the build error in the touch driver caused by a duplicate config name. (synaptics_dsx_96789/Kconfig:19 & synaptics_dsx_96851/Kconfig:25: error: choice value has a prompt outside its choice group)

[Test]
Build and Boot up

MTK-Commit-Id: e1c5d80d738b5ffca2fb455e3a75206f6ac7013d

Signed-off-by: PoShao Chen <poshao.chen@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: I730f2300c8bff5a563122b485f70ee0553220399