[ALPS08309937] cpufreq: fix cpufreq_unregister_driver build break
commit dd329e1e21b5 ("cpufreq: Make cpufreq_unregister_driver()
return void") changes the return type of cpufreq_unregister_driver.
Adapt this change to fix the following build error.

Errors:
drivers/cpufreq/mediatek-cpufreq-hw.c:446:9: error: returning void from a function with incompatible result type int

MTK-Commit-Id: 0e1502d53a5b7804bf9263b20ab2a07b55218614

Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: Iea9d05ef794c7c327fc33c84d23d841947e1122c