[ALPS08309937] flashlight: fix the i2c_client probe argument
Follow commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")
to not taking the id argument.

Errors:
drivers/misc/mediatek/flashlight/v4l2/k6983v1_64_alpha/sy7806.c:927:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/flashlight/v4l2/lm3643.c:1025:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]
drivers/misc/mediatek/flashlight/v4l2/lm3644.c:1059:11: error: incompatible function pointer types initializing int (*)(struct i2c_client *) with an expression of type int (struct i2c_client *, const struct i2c_device_id *) [-Wincompatible-function-pointer-types]

MTK-Commit-Id: ec2f4b1639e7bf79fef949e82b04093ed388d258

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08309937
Feature: Kernel SI Operation
Change-Id: Id5656f7517a85804d82eeae2ed4f83d34f53a9d4
(cherry picked from commit a8a699c4b37e9cf118d26e2394bcbfb244f2712c)